export const defaultUrlImg = "https://image.tmdb.org/t/p/w500";
export const languageList = {
  en: {
    a1: "No data",
    a2: "Previous",
    a3: "404 page not found",
    a4: "Previous home page",
    a5: "Original title",
    a6: "Original language",
    a7: "Genres",
    a8: "Release date",
    a9: "Tagline",
    a10: "Companies",
    a11: "Description",
    a12: "Search",
  },
  ru: {
    a1: "Нет данных",
    a2: "Вернуться назад",
    a3: "404 страница не найдена",
    a4: "Вернутся на главную",
    a5: "Оригинильное название",
    a6: "Оригинильный язык",
    a7: "Жанры",
    a8: "Дата выпуска",
    a9: "Слоган",
    a10: "Компании",
    a11: "Описание",
    a12: "Поиск",
  },
};
